### ISSUE TITLE
Notify Users Of Liked Posts

### ISSUE THREAD

**Issue by Ydnul** [Intro-to-SE-Spring-21/Group5repo#18]
As a user, I want to be able to be notified when someone likes my post.

**Comment by Ydnul** [comment]
Optional Feature that may be used in Sprint 4

**Comment by RachelEJ** [comment]
I'm not sure if we need to do notifications because I'm not sure how we would even implement them.

**Comment by RachelEJ** [comment]
This is unnecessary.
