### ISSUE TITLE
Create a Toggle Button for Follow and Like Button

### ISSUE THREAD

**Issue by Ydnul** [Intro-to-SE-Spring-21/Group5repo#34]
When implementing the follow/like button, there also should be a button to unfollow/unlike a user/post.

**Comment by RachelEJ** [comment]
I think Follow should be a toggle button for sure, but I think we can leave the Like button as a standard increment instead of a toggle.

**Comment by Ydnul** [comment]
Yes we could but we also decided we wanted the information about the user who liked the post.
