### ISSUE TITLE
Determine How To View User Profile

### ISSUE THREAD

**Issue by Ydnul** [Intro-to-SE-Spring-21/Group5repo#35]
User Story can be interpreted in 2 ways. One is view user profile from clicking on profile from tweet. Two is querying/searching for profile and opening page via the database.

**Comment by RachelEJ** [comment]
We will be scrapping the search bar as it is unnecessary. The site will have 1 large public feed and user profiles can be accessed upon selecting a beanz and navigating to their profile through it.
