### ISSUE TITLE
Create A Settings Page

### ISSUE THREAD

**Issue by Ydnul** [Intro-to-SE-Spring-21/Group5repo#52]
An Additional Settings Page that goes with the BeanzCroc theme.

**Comment by RachelEJ** [comment]
I've created a settings.html page but it's currently empty.

**Comment by Ydnul** [comment]
Yes we will need to create the functionality of it as well once it is completed.

**Comment by RachelEJ** [comment]
Added the HTML form elements to the page. Now functionality must be added. Related to #80

**Comment by Jakksan** [comment]
Implemented by Rachel. Needs further back-end work, but functionality is not essential at this time
