### ISSUE TITLE
Create A User Profile and BIO

### ISSUE THREAD

**Issue by Ydnul** [Intro-to-SE-Spring-21/Group5repo#56]
Creates a Page that will Show specific USER INFO and new BIO from settings page.

**Comment by RachelEJ** [comment]
This is more of an optional feature we can add. It'll be tied to #52 and #53

**Comment by Jakksan** [comment]
User Profile implemented. Bio has bugs, so is not in the current version

**Comment by Ydnul** [comment]
We created profiles and added bios.
