### ISSUE TITLE
Our teammate still isn't added to the organization.

### ISSUE THREAD

**Issue by RachelEJ** [Intro-to-SE-Spring-21/Group5repo#6]
Jackson de Gruiter hasn't been added to this organization and thus can't make any edits to this repository. We are unable to add him because the TA hasn't sent out an invite. Until he is added, he will be unable to make any pull requests, comments, or reviews, and thus we will be making edits in his stead.

**Comment by tbw179** [comment]
This is big problem please fix fast

**Comment by Ydnul** [comment]
Yes we are currently missing Jackson de Gruiter. We added his basic info, but we need him to be able to do individual work on the project.

**Comment by RachelEJ** [comment]
He got added
