### ISSUE TITLE
Add functionality to userProfile.html

### ISSUE THREAD

**Issue by RachelEJ** [Intro-to-SE-Spring-21/Group5repo#82]
Made a template for userProfile. Populate the following info:
Username
Handle
Feed
Beanz full text
Likes

Also add functionality to the buttons.

**Comment by RachelEJ** [comment]
Related to #56 and closes #35.

**Comment by RachelEJ** [comment]
Would also like to add that the profile's Feed will display both the user's beanz as well as beanz from any users they follow.

**Comment by Jakksan** [comment]
backlogged to non-existent sprint 5
